language: node_js
node_js:
  - "14.16.0"
before_script:
  - npm install -g @angular/cli
  - npm install
  - cd studybuddies
install:
  - pip install codacy-coverage
script:
  - npm update
  - npm run build
